export const dSNXPoolAddressMainnet = '0x65bb99e80a863e0e27ee6d09c794ed8c0be47186';
export const dSNXPoolAddressOptimism = '0x59babc14dd73761e38e5bda171b2298dc14da92d';
export const dSNXAbi = [
  'event Approval(address indexed owner, address indexed spender, uint256 value)',
  'event Deposit(address fundAddress, address investor, address assetDeposited, uint256 amountDeposited, uint256 valueDeposited, uint256 fundTokensReceived, uint256 totalInvestorFundTokens, uint256 fundValue, uint256 totalSupply, uint256 time)',
  'event ManagerFeeMinted(address pool, address manager, uint256 available, uint256 daoFee, uint256 managerFee, uint256 tokenPriceAtLastFeeMint)',
  'event PoolManagerLogicSet(address poolManagerLogic, address from)',
  'event PoolPrivacyUpdated(bool isPoolPrivate)',
  'event TransactionExecuted(address pool, address manager, uint16 transactionType, uint256 time)',
  'event Transfer(address indexed from, address indexed to, uint256 value)',
  'event Withdrawal(address fundAddress, address investor, uint256 valueWithdrawn, uint256 fundTokensWithdrawn, uint256 totalInvestorFundTokens, uint256 fundValue, uint256 totalSupply, tuple(address asset, uint256 amount, bool externalWithdrawProcessed)[] withdrawnAssets, uint256 time)',
  'function allowance(address owner, address spender) view returns (uint256)',
  'function approve(address spender, uint256 amount) returns (bool)',
  'function availableManagerFee() view returns (uint256 fee)',
  'function availableManagerFeeAndTotalFundValue() view returns (uint256 fee, uint256 fundValue)',
  'function balanceOf(address account) view returns (uint256)',
  'function creationTime() view returns (uint256)',
  'function creator() view returns (address)',
  'function decimals() view returns (uint8)',
  'function decreaseAllowance(address spender, uint256 subtractedValue) returns (bool)',
  'function deposit(address _asset, uint256 _amount) returns (uint256 liquidityMinted)',
  'function execTransaction(address to, bytes data) returns (bool success)',
  'function executeOperation(address[] assets, uint256[] amounts, uint256[] premiums, address originator, bytes params) returns (bool success)',
  'function factory() view returns (address)',
  'function getExitCooldown() view returns (uint256 exitCooldown)',
  'function getExitRemainingCooldown(address sender) view returns (uint256 remaining)',
  'function getFundSummary() view returns (string, uint256, uint256, address, string, uint256, bool, uint256, uint256, uint256, uint256)',
  'function getWithdrawSingleMax(address _asset) view returns (uint256 fundTokenAmount)',
  'function increaseAllowance(address spender, uint256 addedValue) returns (bool)',
  'function initialize(address _factory, bool _privatePool, string _fundName, string _fundSymbol)',
  'function isMemberAllowed(address member) view returns (bool)',
  'function lastDeposit(address) view returns (uint256)',
  'function lastWhitelistTransfer(address) view returns (uint256)',
  'function managerName() view returns (string _managerName)',
  'function mintManagerFee()',
  'function name() view returns (string)',
  'function poolManagerLogic() view returns (address)',
  'function privatePool() view returns (bool)',
  'function setPoolManagerLogic(address _poolManagerLogic) returns (bool)',
  'function setPoolPrivate(bool _privatePool)',
  'function symbol() view returns (string)',
  'function tokenPrice() view returns (uint256 price)',
  'function tokenPriceAtLastFeeMint() view returns (uint256)',
  'function tokenPriceWithoutManagerFee() view returns (uint256 price)',
  'function totalSupply() view returns (uint256)',
  'function transfer(address recipient, uint256 amount) returns (bool)',
  'function transferFrom(address sender, address recipient, uint256 amount) returns (bool)',
  'function withdraw(uint256 _fundTokenAmount)',
  'function withdrawSingle(uint256 _fundTokenAmount, address _asset)',
];
