export const LOCAL_STORAGE_KEYS = {
  SELECTED_WALLET: 'selectedWallet',
  WATCHED_WALLETS: 'watchedWallets',
  THALES_STAKING_INFO_VISIBLE: 'thalesStakingInfo',
  WARNING_URL_BANNER_VISIBLE: 'isWarningUrlBannerVisible',
  RE_ELECTION_NEW_START_TIME: 'reElectionNewStartTimeVisible',
  STAKING_V2_ENABLED: 'STAKING_V2_ENABLED',
};

export const SESSION_STORAGE_KEYS = {
  TERMS_CONDITIONS_ACCEPTED: 'TERMS_CONDITIONS_ACCEPTED',
};
