export const LOCAL_STORAGE_KEYS = {
  SELECTED_WALLET: 'selectedWallet',
  THALES_STAKING_INFO_VISIBLE: 'thalesStakingInfo',
  KWENTA_TOKEN_LIVE: 'KWENTA_TOKEN_LIVE',
  WARNING_URL_BANNER_VISIBLE: 'isWarningUrlBannerVisible',
  RE_ELECTION_NEW_START_TIME: 'reElectionNewStartTimeVisible',
  LIQUIDATION_SETTING_CHANGES: 'LIQUIDATION_SETTING_CHANGES',
  BRIDGING_HISTORY: 'BRIDGING_HISTORY',
};
