import { gql } from 'graphql-request';
import { FeesClaimedParams } from '../../src/types';
import { createGQLWhereString, createGQLBlockNumberString } from '../../src/utils';

export const createFeesClaimedQuery = ({
	account,
	autoGeneratedPaginationField,
	blockNumber,
}: FeesClaimedParams): string => {
	const whereString = createGQLWhereString(
		Object.entries({
			account: account != null ? 'account' : null,
			timestamp_lt: autoGeneratedPaginationField != null ? 'autoGeneratedPaginationField' : null,
		})
	);

	return gql`
		query feesClaimeds($autoGeneratedPaginationField: Int, $max: Int, $account: String) {
			feesClaimeds(
				first: $max${createGQLBlockNumberString(blockNumber)}
				where: ${whereString}
				orderBy: timestamp
				orderDirection: desc
			) {
        id
        account
        value
        rewards
        timestamp
        block
			}
		}
	`;
};
