checksumBehavior: ignore

compressionLevel: mixed

defaultSemverRangePrefix: ^

enableGlobalCache: true

enableTelemetry: false

nodeLinker: node-modules

npmRegistryServer: "https://registry.npmjs.org"

supportedArchitectures:
  cpu:
    - current
    - x64
  libc:
    - glibc
  os:
    - current
    - linux

yarnPath: .yarn/releases/yarn-4.6.0.cjs
