codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

github_checks:
  annotations: no # for now let's not fail the build when coverage decreases

comment:
  layout: 'reach, diff, flags, files'
  behavior: once
  require_changes: false # if true: only post the comment if coverage changes

ignore:
  - '**/*.cy.*'
  - '**/*.test.*'
  - '**/*.e2e.*'
  - '.circleci'
  - '.github'
  - 'packages/'
  - 'tools'
  - 'v1'
  - 'v2'
  - 'babel.config.js'
  - 'jest.config.js'
  - 'jest.global.js'
