export const address = '0x525268dD5cfa17A39839818e9C6375d82d932CC0';
export const abi = [
  'error CapacityLocked(uint256 marketId)',
  'error EmptyDistribution()',
  'error FeatureUnavailable()',
  'error InvalidParameters(string incorrectParameter, string help)',
  'error MarketNotFound(uint128 marketId)',
  'error PoolAlreadyExists(uint128 poolId)',
  'error PoolNotFound(uint128 poolId)',
  'error PoolNotFound(uint128 poolId)',
  'error Unauthorized(address addr)',
  'error ZeroAddress()',
  'event NominatedPoolOwner(uint128 indexed poolId, address indexed owner)',
  'event PoolConfigurationSet(uint128 indexed poolId, tuple(uint128 market, uint128 weight, int128 maxDebtShareValue)[] markets, address indexed sender)',
  'event PoolCreated(uint128 indexed poolId, address indexed owner)',
  'event PoolNameUpdated(uint128 indexed poolId, string indexed name, address indexed sender)',
  'event PoolNominationRenounced(uint128 indexed poolId, address indexed owner)',
  'event PoolNominationRevoked(uint128 indexed poolId, address indexed owner)',
  'event PoolOwnershipAccepted(uint128 indexed poolId, address indexed owner)',
  'event PoolOwnershipRenounced(uint128 indexed poolId, address indexed owner)',
  'function acceptPoolOwnership(uint128 poolId)',
  'function createPool(uint128 requestedPoolId, address owner)',
  'function getMinLiquidityRatio() view returns (uint256)',
  'function getNominatedPoolOwner(uint128 poolId) view returns (address)',
  'function getPoolConfiguration(uint128 poolId) view returns (tuple(uint128 market, uint128 weight, int128 maxDebtShareValue)[])',
  'function getPoolName(uint128 poolId) view returns (string poolName)',
  'function getPoolOwner(uint128 poolId) view returns (address)',
  'function nominatePoolOwner(address nominatedOwner, uint128 poolId)',
  'function renouncePoolNomination(uint128 poolId)',
  'function renouncePoolOwnership(uint128 poolId)',
  'function setMinLiquidityRatio(uint256 minLiquidityRatio)',
  'function setPoolConfiguration(uint128 poolId, tuple(uint128 market, uint128 weight, int128 maxDebtShareValue)[] newDistributions)',
  'function setPoolName(uint128 poolId, string name)',
];
