import { gql } from 'graphql-request';
import { DailyBurnedQueryParams } from '../../src/types';
import { createGQLBlockNumberString } from '../../src/utils';

export const createDailyBurnedQuery = (params?: DailyBurnedQueryParams): string => {
	return gql`
		query DailyBurneds($autoGeneratedPaginationField: Int, $minTimestamp: Int, $max: Int) {
			dailyBurneds(
				first: $max${createGQLBlockNumberString(params?.blockNumber ?? null)}
				orderBy: id
				orderDirection: desc
			) {
        id
        value
				totalDebt
			}
		}
	`;
};
