export const abi = [
  'constructor(address _owner)',
  'event DecimalsUpdated(uint256)',
  'event GasPriceUpdated(uint256)',
  'event L1BaseFeeUpdated(uint256)',
  'event OverheadUpdated(uint256)',
  'event OwnershipTransferred(address indexed previousOwner, address indexed newOwner)',
  'event ScalarUpdated(uint256)',
  'function decimals() view returns (uint256)',
  'function gasPrice() view returns (uint256)',
  'function getL1Fee(bytes _data) view returns (uint256)',
  'function getL1GasUsed(bytes _data) view returns (uint256)',
  'function l1BaseFee() view returns (uint256)',
  'function overhead() view returns (uint256)',
  'function owner() view returns (address)',
  'function renounceOwnership()',
  'function scalar() view returns (uint256)',
  'function setDecimals(uint256 _decimals)',
  'function setGasPrice(uint256 _gasPrice)',
  'function setL1BaseFee(uint256 _baseFee)',
  'function setOverhead(uint256 _overhead)',
  'function setScalar(uint256 _scalar)',
  'function transferOwnership(address newOwner)',
];
export const address = '0x420000000000000000000000000000000000000F';
