name = "synthetix-periphery"
version = "1.0.0"
description = "Synthetix system supplemental contracts"

[setting.owner]
defaultValue = "0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266"

[setting.erc20_version]
defaultValue = "latest"

[setting.synthetix_version]
defaultValue = "1.0.0"

[setting.chainlink_version]
defaultValue = "0.1.0"

[setting.rate_decimals]
defaultValue = "6"

[setting.lusd_rate]
defaultValue = "1000000"

[setting.snx_rate]
defaultValue = "10000000"

[setting.weth_rate]
defaultValue = "100000000"

[import.lusd]
source = "mintableerc20:<%= settings.erc20_version %>"
options.name = "Liquity USD"
options.symbol = "LUSD"

[import.snx]
source = "mintableerc20:<%= settings.erc20_version %>"
options.name = "Synthetix Token"
options.symbol = "SNX"

[import.aggregator_snx]
source = "chainlink:<%= settings.chainlink_version %>"
options.salt = "snx"
options.decimals = "<%= settings.rate_decimals %>"
options.rate = "<%= settings.snx_rate %>"

[import.aggregator_lusd]
source = "chainlink:<%= settings.chainlink_version %>"
options.salt = "lusd"
options.decimals = "<%= settings.rate_decimals %>"
options.rate = "<%= settings.lusd_rate %>"

[import.aggregator_weth]
source = "chainlink:<%= settings.chainlink_version %>"
options.salt = "weth"
options.decimals = "<%= settings.rate_decimals %>"
options.rate = "<%= settings.weth_rate %>"

[import.synthetix]
source = "synthetix-main:<%= settings.synthetix_version %>"
options.owner = "<%= settings.owner %>"

[contract.Multicall]
artifact = "Multicall3"

[contract.WETH]
artifact = "WETH9"

[invoke.register_lusd_collateral]
target = ["synthetix.CoreProxy"]
fromCall.func = "owner"
func = "configureCollateral"
args = [
    "<%= imports.lusd.contracts.token.address %>",
    "<%= imports.aggregator_lusd.contracts.aggregator.address %>",
 "1500000",
    "1100000",
    "1000000000000000000",
    true,
]
depends = ["import.synthetix", "import.lusd", "import.aggregator_lusd"]

[invoke.register_snx_collateral]
target = ["synthetix.CoreProxy"]
fromCall.func = "owner"
func = "configureCollateral"
args = [
    "<%= imports.snx.contracts.token.address %>",
    "<%= imports.aggregator_snx.contracts.aggregator.address %>",
    "4000000",
    "2000000",
    "1000000000000000000",
    true,
]
depends = ["import.synthetix", "import.snx", "import.aggregator_snx"]

[invoke.register_weth_collateral]
target = ["synthetix.CoreProxy"]
fromCall.func = "owner"
func = "configureCollateral"
args = [
    "<%= contracts.WETH.address %>",
    "<%= imports.aggregator_weth.contracts.aggregator.address %>",
    "3000000",
    "1500000",
    "1000000000000000000",
    true,
]
depends = ["import.synthetix", "contract.WETH", "import.aggregator_weth"]

[invoke.mint_snx]
target = ["snx.token"]
func = "mint"
args = [
    # change to your address for some SNX
    "0x70997970C51812dc3A010C7d01b50e0d17dc79C8",
    "200000000000000000000"
]
depends=["import.snx", "import.synthetix"]

[invoke.createPreferredPool]
target = ["synthetix.CoreProxy"]
func = "createPool"
args = [
    1,
    "<%= settings.owner %>",
]
depends=["import.synthetix"]

[invoke.setPreferredPool]
target = ["synthetix.CoreProxy"]
func = "setPreferredPool"
from = "<%= settings.owner %>"
args = [
    1,
]
depends=["invoke.createPreferredPool"]
