// !!! DO NOT EDIT !!! Automatically generated file

export const name = 'Depot';
export const address = '0x91112d49095Febf1616af25be7f32Cf580DBC7A3';
export const source = 'Depot';
export const abi = [
  'constructor(address _owner, address _fundsWallet, address _resolver)',
  'event CacheUpdated(bytes32 name, address destination)',
  'event ClearedDeposit(address indexed fromAddress, address indexed toAddress, uint256 fromETHAmount, uint256 toAmount, uint256 indexed depositIndex)',
  'event Exchange(string fromCurrency, uint256 fromAmount, string toCurrency, uint256 toAmount)',
  'event FundsWalletUpdated(address newFundsWallet)',
  'event MaxEthPurchaseUpdated(uint256 amount)',
  'event MinimumDepositAmountUpdated(uint256 amount)',
  'event NonPayableContract(address indexed receiver, uint256 amount)',
  'event OwnerChanged(address oldOwner, address newOwner)',
  'event OwnerNominated(address newOwner)',
  'event PauseChanged(bool isPaused)',
  'event SynthDeposit(address indexed user, uint256 amount, uint256 indexed depositIndex)',
  'event SynthDepositNotAccepted(address user, uint256 amount, uint256 minimum)',
  'event SynthDepositRemoved(address indexed user, uint256 amount, uint256 indexed depositIndex)',
  'event SynthWithdrawal(address user, uint256 amount)',
  'function acceptOwnership()',
  'function depositEndIndex() view returns (uint256)',
  'function depositStartIndex() view returns (uint256)',
  'function depositSynths(uint256 amount)',
  'function deposits(uint256) view returns (address user, uint256 amount)',
  'function exchangeEtherForSNX() payable returns (uint256)',
  'function exchangeEtherForSNXAtRate(uint256 guaranteedEtherRate, uint256 guaranteedSynthetixRate) payable returns (uint256)',
  'function exchangeEtherForSynths() payable returns (uint256)',
  'function exchangeEtherForSynthsAtRate(uint256 guaranteedRate) payable returns (uint256)',
  'function exchangeSynthsForSNX(uint256 synthAmount) returns (uint256)',
  'function exchangeSynthsForSNXAtRate(uint256 synthAmount, uint256 guaranteedRate) returns (uint256)',
  'function fundsWallet() view returns (address)',
  'function isResolverCached() view returns (bool)',
  'function lastPauseTime() view returns (uint256)',
  'function maxEthPurchase() view returns (uint256)',
  'function minimumDepositAmount() view returns (uint256)',
  'function nominateNewOwner(address _owner)',
  'function nominatedOwner() view returns (address)',
  'function owner() view returns (address)',
  'function paused() view returns (bool)',
  'function rebuildCache()',
  'function resolver() view returns (address)',
  'function resolverAddressesRequired() view returns (bytes32[] addresses)',
  'function setFundsWallet(address _fundsWallet)',
  'function setMaxEthPurchase(uint256 _maxEthPurchase)',
  'function setMinimumDepositAmount(uint256 _amount)',
  'function setPaused(bool _paused)',
  'function smallDeposits(address) view returns (uint256)',
  'function synthetixReceivedForEther(uint256 amount) view returns (uint256)',
  'function synthetixReceivedForSynths(uint256 amount) view returns (uint256)',
  'function synthsReceivedForEther(uint256 amount) view returns (uint256)',
  'function totalSellableDeposits() view returns (uint256)',
  'function withdrawMyDepositedSynths()',
  'function withdrawSynthetix(uint256 amount)',
];
