export const name = 'FuturesMarketSettings';
export const address = '0xaE55F163337A2A46733AA66dA9F35299f9A46e9e';
export const source = 'FuturesMarketSettings';
export const abi = [
  'constructor(address _owner, address _resolver)',
  'event CacheUpdated(bytes32 name, address destination)',
  'event LiquidationBufferRatioUpdated(uint256 bps)',
  'event LiquidationFeeRatioUpdated(uint256 bps)',
  'event MinInitialMarginUpdated(uint256 minMargin)',
  'event MinKeeperFeeUpdated(uint256 sUSD)',
  'event OwnerChanged(address oldOwner, address newOwner)',
  'event OwnerNominated(address newOwner)',
  'event ParameterUpdated(bytes32 indexed marketKey, bytes32 indexed parameter, uint256 value)',
  'function acceptOwnership()',
  'function isResolverCached() view returns (bool)',
  'function liquidationBufferRatio() view returns (uint256)',
  'function liquidationFeeRatio() view returns (uint256)',
  'function makerFee(bytes32 _marketKey) view returns (uint256)',
  'function makerFeeNextPrice(bytes32 _marketKey) view returns (uint256)',
  'function maxFundingRate(bytes32 _marketKey) view returns (uint256)',
  'function maxLeverage(bytes32 _marketKey) view returns (uint256)',
  'function maxMarketValueUSD(bytes32 _marketKey) view returns (uint256)',
  'function minInitialMargin() view returns (uint256)',
  'function minKeeperFee() view returns (uint256)',
  'function nextPriceConfirmWindow(bytes32 _marketKey) view returns (uint256)',
  'function nominateNewOwner(address _owner)',
  'function nominatedOwner() view returns (address)',
  'function owner() view returns (address)',
  'function parameters(bytes32 _marketKey) view returns (uint256 takerFee, uint256 makerFee, uint256 takerFeeNextPrice, uint256 makerFeeNextPrice, uint256 nextPriceConfirmWindow, uint256 maxLeverage, uint256 maxMarketValueUSD, uint256 maxFundingRate, uint256 skewScaleUSD)',
  'function rebuildCache()',
  'function resolver() view returns (address)',
  'function resolverAddressesRequired() view returns (bytes32[] addresses)',
  'function setLiquidationBufferRatio(uint256 _ratio)',
  'function setLiquidationFeeRatio(uint256 _ratio)',
  'function setMakerFee(bytes32 _marketKey, uint256 _makerFee)',
  'function setMakerFeeNextPrice(bytes32 _marketKey, uint256 _makerFeeNextPrice)',
  'function setMaxFundingRate(bytes32 _marketKey, uint256 _maxFundingRate)',
  'function setMaxLeverage(bytes32 _marketKey, uint256 _maxLeverage)',
  'function setMaxMarketValueUSD(bytes32 _marketKey, uint256 _maxMarketValueUSD)',
  'function setMinInitialMargin(uint256 _minMargin)',
  'function setMinKeeperFee(uint256 _sUSD)',
  'function setNextPriceConfirmWindow(bytes32 _marketKey, uint256 _nextPriceConfirmWindow)',
  'function setParameters(bytes32 _marketKey, uint256 _takerFee, uint256 _makerFee, uint256 _takerFeeNextPrice, uint256 _makerFeeNextPrice, uint256 _nextPriceConfirmWindow, uint256 _maxLeverage, uint256 _maxMarketValueUSD, uint256 _maxFundingRate, uint256 _skewScaleUSD)',
  'function setSkewScaleUSD(bytes32 _marketKey, uint256 _skewScaleUSD)',
  'function setTakerFee(bytes32 _marketKey, uint256 _takerFee)',
  'function setTakerFeeNextPrice(bytes32 _marketKey, uint256 _takerFeeNextPrice)',
  'function skewScaleUSD(bytes32 _marketKey) view returns (uint256)',
  'function takerFee(bytes32 _marketKey) view returns (uint256)',
  'function takerFeeNextPrice(bytes32 _marketKey) view returns (uint256)',
];
