export const name = 'SynthetixDebtShare';
export const address = '0x45c55BF488D3Cb8640f12F63CbeDC027E8261E79';
export const source = 'SynthetixDebtShare';
export const abi = [
  'constructor(address _owner, address _resolver)',
  'event Burn(address indexed account, uint256 amount)',
  'event CacheUpdated(bytes32 name, address destination)',
  'event ChangeAuthorizedBroker(address indexed authorizedBroker, bool authorized)',
  'event ChangeAuthorizedToSnapshot(address indexed authorizedToSnapshot, bool authorized)',
  'event Mint(address indexed account, uint256 amount)',
  'event OwnerChanged(address oldOwner, address newOwner)',
  'event OwnerNominated(address newOwner)',
  'event Transfer(address indexed from, address indexed to, uint256 value)',
  'function CONTRACT_NAME() view returns (bytes32)',
  'function acceptOwnership()',
  'function addAuthorizedBroker(address target)',
  'function addAuthorizedToSnapshot(address target)',
  'function allowance(address, address spender) view returns (uint256)',
  'function approve(address, uint256) pure returns (bool)',
  'function authorizedBrokers(address) view returns (bool)',
  'function authorizedToSnapshot(address) view returns (bool)',
  'function balanceOf(address account) view returns (uint256)',
  'function balanceOfOnPeriod(address account, uint256 periodId) view returns (uint256)',
  'function balances(address, uint256) view returns (uint128 amount, uint128 periodId)',
  'function burnShare(address account, uint256 amount)',
  'function currentPeriodId() view returns (uint128)',
  'function decimals() view returns (uint8)',
  'function finishSetup()',
  'function importAddresses(address[] accounts, uint256[] amounts)',
  'function isInitialized() view returns (bool)',
  'function isResolverCached() view returns (bool)',
  'function mintShare(address account, uint256 amount)',
  'function name() view returns (string)',
  'function nominateNewOwner(address _owner)',
  'function nominatedOwner() view returns (address)',
  'function owner() view returns (address)',
  'function rebuildCache()',
  'function removeAuthorizedBroker(address target)',
  'function removeAuthorizedToSnapshot(address target)',
  'function resolver() view returns (address)',
  'function resolverAddressesRequired() view returns (bytes32[] addresses)',
  'function sharePercent(address account) view returns (uint256)',
  'function sharePercentOnPeriod(address account, uint256 periodId) view returns (uint256)',
  'function symbol() view returns (string)',
  'function takeSnapshot(uint128 id)',
  'function totalSupply() view returns (uint256)',
  'function totalSupplyOnPeriod(uint256) view returns (uint256)',
  'function transfer(address, uint256) pure returns (bool)',
  'function transferFrom(address from, address to, uint256 amount) returns (bool)',
];
