export const address = '0xd5e897FD0b170573cf1473D4462e517D0b8D8329';
export const abi = [
  'error EmptyVault(uint256 fundId, address collateralType)',
  'error FailedTransfer(address from, address to, uint256 value)',
  'error FundAlreadyApproved(uint256 fundId)',
  'error FundAlreadyExists(uint256 fundId)',
  'error FundNotFound(uint256 fundId)',
  'error IneligibleForLiquidation(uint256 collateralValue, uint256 debt, uint256 currentCRatio, uint256 cratio)',
  'error InsufficientAccountCollateral(uint256 accountId, address collateralType, uint256 requestedAmount)',
  'error InvalidCollateralType(address collateralType)',
  'error InvalidParameters(string incorrectParameter, string help)',
  'error InvalidParameters(string incorrectParameter, string help)',
  'error OnlyTokenProxyAllowed(address origin)',
  'event DelegationUpdated(bytes32 liquidityItemId, uint256 accountId, uint256 fundId, address collateralType, uint256 amount, uint256 leverage)',
  'event FundApprovedAdded(uint256 fundId)',
  'event FundApprovedRemoved(uint256 fundId)',
  'event FundCreated(address owner, uint256 fundId)',
  'event FundPositionSet(uint256 fundId, uint256[] markets, uint256[] weights, address executedBy)',
  'event Liquidation(uint256 indexed accountId, uint256 indexed fundId, address indexed collateralType, uint256 debtLiquidated, uint256 collateralLiquidated, uint256 amountRewarded)',
  'event NominatedNewOwner(address nominatedOwner, uint256 fundId)',
  'event OwnershipAccepted(address newOwner, uint256 fundId)',
  'event OwnershipRenounced(address target, uint256 fundId)',
  'event PreferredFundSet(uint256 fundId)',
  'event RewardDistributionSet(uint256 indexed fundId, address indexed token, uint256 indexed index, address distributor, uint256 totalRewarded, uint256 start, uint256 duration)',
  'event RewardsClaimed(uint256 indexed fundId, address indexed token, uint256 indexed accountId, uint256 index, uint256 amountClaimed)',
  'function isLiquidatable(uint256 accountId, uint256 fundId, address collateralType) returns (bool)',
  'function liquidate(uint256 accountId, uint256 fundId, address collateralType) returns (uint256 amountRewarded, uint256 debtLiquidated, uint256 collateralLiquidated)',
  'function liquidateVault(uint256 fundId, address collateralType) returns (uint256 amountRewarded, uint256 collateralLiquidated)',
];
