export const address = '0xdFF429361B28C7F41c400A1EAA172E8A17fD4752';
export const abi = [
  'error InvalidParameters(string incorrectParameter, string help)',
  'error MarketDepositNotApproved(address market, address from, uint256 requestedAmount, uint256 approvedAmount)',
  'error MismatchAssociatedSystemKind(bytes32 expected, bytes32 actual)',
  'error NotEnoughLiquidity(uint128 marketId, uint256 amount)',
  'error Unauthorized(address addr)',
  'event MarketRegistered(address indexed market, uint128 indexed marketId)',
  'event UsdDeposited(uint128 indexed marketId, address indexed target, uint256 amount, address indexed sender)',
  'event UsdWithdrawn(uint128 indexed marketId, address indexed target, uint256 amount, address indexed sender)',
  'function depositUsd(uint128 marketId, address target, uint256 amount)',
  'function getMarketCollateral(uint128 marketId) view returns (uint256)',
  'function getMarketDebtPerShare(uint128 marketId) returns (int256)',
  'function getMarketIssuance(uint128 marketId) view returns (int128)',
  'function getMarketReportedDebt(uint128 marketId) view returns (uint256)',
  'function getMarketTotalBalance(uint128 marketId) view returns (int256)',
  'function getWithdrawableUsd(uint128 marketId) view returns (uint256)',
  'function registerMarket(address market) returns (uint128 marketId)',
  'function withdrawUsd(uint128 marketId, address target, uint256 amount)',
];
