// !!! DO NOT EDIT !!! Automatically generated file

export const name = 'Depot';
export const address = '0xE1f64079aDa6Ef07b03982Ca34f1dD7152AA3b86';
export const source = 'Depot';
export const abi = [
  'function exchangeEtherForSNX() payable returns (uint256)',
  'function resolver() view returns (address)',
  'function minimumDepositAmount() view returns (uint256)',
  'function exchangeEtherForSynthsAtRate(uint256 guaranteedRate) payable returns (uint256)',
  'function synthsReceivedForEther(uint256 amount) view returns (uint256)',
  'function nominateNewOwner(address _owner)',
  'function setPaused(bool _paused)',
  'function initiationTime() view returns (uint256)',
  'function exchangeEtherForSynths() payable returns (uint256)',
  'function setSelfDestructBeneficiary(address _beneficiary)',
  'function fundsWallet() view returns (address)',
  'function terminateSelfDestruct()',
  'function totalSellableDeposits() view returns (uint256)',
  'function setResolver(address _resolver)',
  'function nominatedOwner() view returns (address)',
  'function paused() view returns (bool)',
  'function setFundsWallet(address _fundsWallet)',
  'function depositStartIndex() view returns (uint256)',
  'function acceptOwnership()',
  'function withdrawMyDepositedSynths()',
  'function owner() view returns (address)',
  'function lastPauseTime() view returns (uint256)',
  'function exchangeEtherForSNXAtRate(uint256 guaranteedEtherRate, uint256 guaranteedSynthetixRate) payable returns (uint256)',
  'function selfDestruct()',
  'function synthetixReceivedForSynths(uint256 amount) view returns (uint256)',
  'function SELFDESTRUCT_DELAY() view returns (uint256)',
  'function setMinimumDepositAmount(uint256 _amount)',
  'function deposits(uint256) view returns (address user, uint256 amount)',
  'function exchangeSynthsForSNXAtRate(uint256 synthAmount, uint256 guaranteedRate) returns (uint256)',
  'function maxEthPurchase() view returns (uint256)',
  'function selfDestructInitiated() view returns (bool)',
  'function setMaxEthPurchase(uint256 _maxEthPurchase)',
  'function initiateSelfDestruct()',
  'function selfDestructBeneficiary() view returns (address)',
  'function smallDeposits(address) view returns (uint256)',
  'function synthetixReceivedForEther(uint256 amount) view returns (uint256)',
  'function depositSynths(uint256 amount)',
  'function withdrawSynthetix(uint256 amount)',
  'function exchangeSynthsForSNX(uint256 synthAmount) returns (uint256)',
  'function depositEndIndex() view returns (uint256)',
  'constructor(address _owner, address _fundsWallet, address _resolver)',
  'event MaxEthPurchaseUpdated(uint256 amount)',
  'event FundsWalletUpdated(address newFundsWallet)',
  'event Exchange(string fromCurrency, uint256 fromAmount, string toCurrency, uint256 toAmount)',
  'event SynthWithdrawal(address user, uint256 amount)',
  'event SynthDeposit(address indexed user, uint256 amount, uint256 indexed depositIndex)',
  'event SynthDepositRemoved(address indexed user, uint256 amount, uint256 indexed depositIndex)',
  'event SynthDepositNotAccepted(address user, uint256 amount, uint256 minimum)',
  'event MinimumDepositAmountUpdated(uint256 amount)',
  'event NonPayableContract(address indexed receiver, uint256 amount)',
  'event ClearedDeposit(address indexed fromAddress, address indexed toAddress, uint256 fromETHAmount, uint256 toAmount, uint256 indexed depositIndex)',
  'event PauseChanged(bool isPaused)',
  'event SelfDestructTerminated()',
  'event SelfDestructed(address beneficiary)',
  'event SelfDestructInitiated(uint256 selfDestructDelay)',
  'event SelfDestructBeneficiaryUpdated(address newBeneficiary)',
  'event OwnerNominated(address newOwner)',
  'event OwnerChanged(address oldOwner, address newOwner)',
];
