// !!! DO NOT EDIT !!! Automatically generated file

export const name = 'EtherWrapper';
export const address = '0x858A2FF0EAe5fcb0be10df79B741Cff89B77FeCB';
export const source = 'EmptyEtherWrapper';
export const abi = [
  'constructor()',
  'function distributeFees()',
  'function totalIssuedSynths() view returns (uint256)',
];
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from 'ethers';
import type { FunctionFragment, Result } from '@ethersproject/abi';
import type { Listener, Provider } from '@ethersproject/providers';
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from './common';

export interface EtherWrapperInterface extends utils.Interface {
  functions: {
    'distributeFees()': FunctionFragment;
    'totalIssuedSynths()': FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: 'distributeFees' | 'totalIssuedSynths'): FunctionFragment;

  encodeFunctionData(functionFragment: 'distributeFees', values?: undefined): string;
  encodeFunctionData(functionFragment: 'totalIssuedSynths', values?: undefined): string;

  decodeFunctionResult(functionFragment: 'distributeFees', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'totalIssuedSynths', data: BytesLike): Result;

  events: {};
}

export interface EtherWrapper extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: EtherWrapperInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(eventFilter: TypedEventFilter<TEvent>): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    distributeFees(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    totalIssuedSynths(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  distributeFees(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  totalIssuedSynths(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    distributeFees(overrides?: CallOverrides): Promise<void>;

    totalIssuedSynths(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    distributeFees(overrides?: Overrides & { from?: PromiseOrValue<string> }): Promise<BigNumber>;

    totalIssuedSynths(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    distributeFees(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    totalIssuedSynths(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
