export const address = '0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9';
export const abi = [
  'error FundAlreadyApproved(uint256 fundId)',
  'error FundAlreadyExists(uint256 fundId)',
  'error FundNotFound(uint256 fundId)',
  'error InsufficientAvailableCollateral(uint256 accountId, address collateralType, uint256 requestedAmount)',
  'error InvalidCollateralType(address collateralType)',
  'error InvalidParameters()',
  'error OnlyTokenProxyAllowed(address origin)',
  'error PositionOutOfBounds()',
  'error RoleNotAuthorized(uint256 accountId, bytes32 role, address target)',
  'error Unauthorized(address addr)',
  'error ZeroAddress()',
  'event DelegationUpdated(bytes32 liquidityItemId, uint256 accountId, uint256 fundId, address collateralType, uint256 amount, uint256 leverage)',
  'event FundApprovedAdded(uint256 fundId)',
  'event FundApprovedRemoved(uint256 fundId)',
  'event FundCreated(address owner, uint256 fundId)',
  'event FundPositionSet(uint256 fundId, uint256[] markets, uint256[] weights, address executedBy)',
  'event NominatedNewOwner(address nominatedOwner, uint256 fundId)',
  'event OwnershipAccepted(address newOwner, uint256 fundId)',
  'event OwnershipRenounced(address target, uint256 fundId)',
  'event PositionAdded(bytes32 liquidityItemId, uint256 accountId, uint256 fundId, address collateralType, uint256 amount, uint256 leverage, uint256 shares, uint256 initialDebt)',
  'event PositionDecreased(bytes32 liquidityItemId, uint256 fundId, address collateralType, uint256 amount, uint256 leverage, uint256 shares, uint256 initialDebt)',
  'event PositionIncreased(bytes32 liquidityItemId, uint256 fundId, address collateralType, uint256 amount, uint256 leverage, uint256 shares, uint256 initialDebt)',
  'event PositionRemoved(bytes32 liquidityItemId, uint256 accountId, uint256 fundId, address collateralType)',
  'event PreferredFundSet(uint256 fundId)',
  'function acceptFundOwnership(uint256 fundId)',
  'function createFund(uint256 requestedFundId, address owner)',
  'function getFundName(uint256 fundId) view returns (string fundName)',
  'function getFundPosition(uint256 fundId) view returns (uint256[], uint256[], uint256[])',
  'function nominateNewFundOwner(address nominatedOwner, uint256 fundId)',
  'function nominatedOwnerOf(uint256 fundId) view returns (address)',
  'function ownerOf(uint256 fundId) view returns (address)',
  'function renounceFundNomination(uint256 fundId)',
  'function setFundName(uint256 fundId, string name)',
  'function setFundPosition(uint256 fundId, uint256[] markets, uint256[] weights, uint256[] maxDebtShareValues)',
];
