export const address = '0xF473aaF2545db1491153a8f67733555cF5858788';
export const abi = [
  'error FundAlreadyApproved(uint256 fundId)',
  'error FundAlreadyExists(uint256 fundId)',
  'error FundNotFound(uint256 fundId)',
  'error InsufficientAvailableCollateral(uint256 accountId, address collateralType, uint256 requestedAmount)',
  'error InvalidCollateralType(address collateralType)',
  'error InvalidLeverage(uint256 leverage)',
  'error InvalidParameters()',
  'error MismatchAssociatedSystemKind(bytes32 expected, bytes32 actual)',
  'error OnlyTokenProxyAllowed(address origin)',
  'error PositionOutOfBounds()',
  'error RoleNotAuthorized(uint256 accountId, bytes32 role, address target)',
  'error Unauthorized(address addr)',
  'error ValueAlreadyInSet()',
  'error ValueNotInSet()',
  'event DelegationUpdated(bytes32 liquidityItemId, uint256 accountId, uint256 fundId, address collateralType, uint256 amount, uint256 leverage)',
  'event FundApprovedAdded(uint256 fundId)',
  'event FundApprovedRemoved(uint256 fundId)',
  'event FundCreated(address owner, uint256 fundId)',
  'event FundPositionSet(uint256 fundId, uint256[] markets, uint256[] weights, address executedBy)',
  'event NominatedNewOwner(address nominatedOwner, uint256 fundId)',
  'event OwnershipAccepted(address newOwner, uint256 fundId)',
  'event OwnershipRenounced(address target, uint256 fundId)',
  'event PositionAdded(bytes32 liquidityItemId, uint256 accountId, uint256 fundId, address collateralType, uint256 amount, uint256 leverage, uint256 shares, uint256 initialDebt)',
  'event PositionDecreased(bytes32 liquidityItemId, uint256 fundId, address collateralType, uint256 amount, uint256 leverage, uint256 shares, uint256 initialDebt)',
  'event PositionIncreased(bytes32 liquidityItemId, uint256 fundId, address collateralType, uint256 amount, uint256 leverage, uint256 shares, uint256 initialDebt)',
  'event PositionRemoved(bytes32 liquidityItemId, uint256 accountId, uint256 fundId, address collateralType)',
  'event PreferredFundSet(uint256 fundId)',
  'event RewardsClaimed(uint256 indexed fundId, address indexed token, uint256 indexed accountId, uint256 index, uint256 amountClaimed)',
  'event RewardsDistributionSet(uint256 indexed fundId, address indexed token, uint256 indexed index, address distributor, uint256 totalRewarded, uint256 start, uint256 duration)',
  'function accountFundCollateralValue(uint256 accountId, uint256 fundId, address collateralType) view returns (uint256)',
  'function accountFundDebt(uint256 accountId, uint256 fundId, address collateralType) view returns (uint256)',
  'function burnUSD(uint256 accountId, uint256 fundId, address collateralType, uint256 amount)',
  'function claimRewards(uint256 fundId, address collateralType, uint256 accountId)',
  'function collateralizationRatio(uint256 accountId, uint256 fundId, address collateralType) view returns (uint256)',
  'function debtPerShare(uint256 fundId, address collateralType) view returns (uint256)',
  'function delegateCollateral(uint256 accountId, uint256 fundId, address collateralType, uint256 amount, uint256 leverage)',
  'function distributeRewards(uint256 fundId, address collateralType, uint256 index, address distributor, uint256 amount, uint256 start, uint256 duration)',
  'function fundDebt(uint256 fundId, address collateralType) view returns (uint256)',
  'function getAccountLiquidityItemIds(uint256 accountId) view returns (bytes32[] liquidityItemIds)',
  'function getAccountLiquidityItems(uint256 accountId) view returns (tuple(uint256 accountId, address collateralType, uint256 fundId, uint256 collateralAmount, uint256 shares, uint256 initialDebt, uint256 leverage)[] liquidityItems)',
  'function getAvailableRewards(uint256 fundId, address token, uint256 accountId) returns (uint256[])',
  'function getLiquidityItem(bytes32 liquidityItemId) view returns (tuple(uint256 accountId, address collateralType, uint256 fundId, uint256 collateralAmount, uint256 shares, uint256 initialDebt, uint256 leverage) liquidityItem)',
  'function mintUSD(uint256 accountId, uint256 fundId, address collateralType, uint256 amount)',
  'function totalDebtShares(uint256 fundId, address collateralType) view returns (uint256)',
];
