export const address = '0x94597307C9549c5BB03d1434dBb2301611ACaaB1';
export const abi = [
  'error EmptyVault(uint256 poolId, address collateralType)',
  'error InsufficientAccountCollateral(uint256 accountId, address collateralType, uint256 requestedAmount)',
  'error InvalidCollateralType(address collateralType)',
  'error InvalidParameters(string incorrectParameter, string help)',
  'error InvalidParameters(string incorrectParameter, string help)',
  'error MarketNotFound(uint256 marketId)',
  'error MaxDebtPerShareTooLow(uint256 marketId, int256 requestedMaxDebtPerShare, int256 maximumMaxDebtPerShare)',
  'error OnlyTokenProxyAllowed(address origin)',
  'error PermissionDenied(uint256 accountId, bytes32 permission, address target)',
  'error PoolAlreadyApproved(uint256 poolId)',
  'error PoolAlreadyExists(uint256 poolId)',
  'error PoolNotFound(uint256 poolId)',
  'error Unauthorized(address addr)',
  'error ZeroAddress()',
  'event DelegationUpdated(uint256 accountId, uint256 poolId, address collateralType, uint256 amount, uint256 leverage)',
  'event NominatedNewOwner(address nominatedOwner, uint256 poolId)',
  'event OwnershipAccepted(address newOwner, uint256 poolId)',
  'event OwnershipRenounced(address target, uint256 poolId)',
  'event PoolApprovedAdded(uint256 poolId)',
  'event PoolApprovedRemoved(uint256 poolId)',
  'event PoolCreated(address owner, uint256 poolId)',
  'event PoolPositionSet(uint256 poolId, uint256[] markets, uint256[] weights, address executedBy)',
  'event PreferredPoolSet(uint256 poolId)',
  'event RewardDistributionSet(uint256 indexed poolId, address indexed token, uint256 indexed index, address distributor, uint256 totalRewarded, uint256 start, uint256 duration)',
  'event RewardsClaimed(uint256 indexed poolId, address indexed token, uint256 indexed accountId, uint256 index, uint256 amountClaimed)',
  'function acceptPoolOwnership(uint256 poolId)',
  'function createPool(uint256 requestedPoolId, address owner)',
  'function getMinLiquidityRatio() view returns (uint256)',
  'function getPoolName(uint256 poolId) view returns (string poolName)',
  'function getPoolPosition(uint256 poolId) view returns (uint256[], uint256[], int256[])',
  'function nominateNewPoolOwner(address nominatedOwner, uint256 poolId)',
  'function nominatedOwnerOf(uint256 poolId) view returns (address)',
  'function ownerOf(uint256 poolId) view returns (address)',
  'function renouncePoolNomination(uint256 poolId)',
  'function setMinLiquidityRatio(uint256 minLiquidityRatio)',
  'function setPoolName(uint256 poolId, string name)',
  'function setPoolPosition(uint256 poolId, uint256[] markets, uint256[] weights, int256[] maxDebtShareValues)',
];
