export const address = '0xbcAe82DABb21E6211d952aFcc2742fd7F4737f88';
export const abi = [
  'error EmptyVault(uint256 poolId, address collateralType)',
  'error InsufficientAccountCollateral(uint256 accountId, address collateralType, uint256 requestedAmount)',
  'error InsufficientCollateralRatio(uint256 collateralValue, uint256 debt, uint256 ratio, uint256 minRatio)',
  'error InsufficientDebt(int256 currentDebt)',
  'error InvalidCollateralType(address collateralType)',
  'error InvalidLeverage(uint256 leverage)',
  'error InvalidParameters(string incorrectParameter, string help)',
  'error InvalidParameters(string incorrectParameter, string help)',
  'error MarketNotFound(uint256 marketId)',
  'error MaxDebtPerShareTooLow(uint256 marketId, int256 requestedMaxDebtPerShare, int256 maximumMaxDebtPerShare)',
  'error MismatchAssociatedSystemKind(bytes32 expected, bytes32 actual)',
  'error OnlyTokenProxyAllowed(address origin)',
  'error PermissionDenied(uint256 accountId, bytes32 permission, address target)',
  'error PoolAlreadyApproved(uint256 poolId)',
  'error PoolAlreadyExists(uint256 poolId)',
  'error PoolNotFound(uint256 poolId)',
  'event DelegationUpdated(uint256 accountId, uint256 poolId, address collateralType, uint256 amount, uint256 leverage)',
  'event NominatedNewOwner(address nominatedOwner, uint256 poolId)',
  'event OwnershipAccepted(address newOwner, uint256 poolId)',
  'event OwnershipRenounced(address target, uint256 poolId)',
  'event PoolApprovedAdded(uint256 poolId)',
  'event PoolApprovedRemoved(uint256 poolId)',
  'event PoolCreated(address owner, uint256 poolId)',
  'event PoolPositionSet(uint256 poolId, uint256[] markets, uint256[] weights, address executedBy)',
  'event PreferredPoolSet(uint256 poolId)',
  'event RewardDistributionSet(uint256 indexed poolId, address indexed token, uint256 indexed index, address distributor, uint256 totalRewarded, uint256 start, uint256 duration)',
  'event RewardsClaimed(uint256 indexed poolId, address indexed token, uint256 indexed accountId, uint256 index, uint256 amountClaimed)',
  'function accountCollateralRatio(uint256 accountId, uint256 poolId, address collateralType) returns (uint256)',
  'function accountVaultCollateral(uint256 accountId, uint256 poolId, address collateralType) view returns (uint256 amount, uint256 value, uint256 shares)',
  'function accountVaultDebt(uint256 accountId, uint256 poolId, address collateralType) returns (int256)',
  'function burnUSD(uint256 accountId, uint256 poolId, address collateralType, uint256 amount)',
  'function delegateCollateral(uint256 accountId, uint256 poolId, address collateralType, uint256 collateralAmount, uint256 leverage)',
  'function mintUSD(uint256 accountId, uint256 poolId, address collateralType, uint256 amount)',
  'function totalVaultShares(uint256 poolId, address collateralType) view returns (uint256)',
  'function vaultCollateral(uint256 poolId, address collateralType) view returns (uint256 amount, uint256 value)',
  'function vaultCollateralRatio(uint256 poolId, address collateralType) returns (uint256)',
  'function vaultDebt(uint256 poolId, address collateralType) returns (int256)',
];
