export const name = 'CollateralShort';
export const address = '0x1F2c3a1046c32729862fcB038369696e3273a516';
export const source = 'CollateralShort';
export const abi = [
  'constructor(address _state, address _owner, address _manager, address _resolver, bytes32 _collateralKey, uint256 _minCratio, uint256 _minCollateral)',
  'event CacheUpdated(bytes32 name, address destination)',
  'event CanOpenLoansUpdated(bool canOpenLoans)',
  'event CollateralDeposited(address indexed account, uint256 id, uint256 amountDeposited, uint256 collateralAfter)',
  'event CollateralWithdrawn(address indexed account, uint256 id, uint256 amountWithdrawn, uint256 collateralAfter)',
  'event InteractionDelayUpdated(uint256 interactionDelay)',
  'event IssueFeeRateUpdated(uint256 issueFeeRate)',
  'event LoanClosed(address indexed account, uint256 id)',
  'event LoanClosedByLiquidation(address indexed account, uint256 id, address indexed liquidator, uint256 amountLiquidated, uint256 collateralLiquidated)',
  'event LoanCreated(address indexed account, uint256 id, uint256 amount, uint256 collateral, bytes32 currency, uint256 issuanceFee)',
  'event LoanDrawnDown(address indexed account, uint256 id, uint256 amount)',
  'event LoanPartiallyLiquidated(address indexed account, uint256 id, address liquidator, uint256 amountLiquidated, uint256 collateralLiquidated)',
  'event LoanRepaymentMade(address indexed account, address indexed repayer, uint256 id, uint256 amountRepaid, uint256 amountAfter)',
  'event ManagerUpdated(address manager)',
  'event MaxLoansPerAccountUpdated(uint256 maxLoansPerAccount)',
  'event MinCollateralUpdated(uint256 minCollateral)',
  'event MinCratioRatioUpdated(uint256 minCratio)',
  'event OwnerChanged(address oldOwner, address newOwner)',
  'event OwnerNominated(address newOwner)',
  'function acceptOwnership()',
  'function addRewardsContracts(address rewardsContract, bytes32 synth)',
  'function addSynths(bytes32[] _synthNamesInResolver, bytes32[] _synthKeys)',
  'function areSynthsAndCurrenciesSet(bytes32[] _synthNamesInResolver, bytes32[] _synthKeys) view returns (bool)',
  'function canOpenLoans() view returns (bool)',
  'function close(uint256 id)',
  'function collateralKey() view returns (bytes32)',
  'function collateralRatio(tuple(uint256 id, address account, uint256 collateral, bytes32 currency, uint256 amount, bool short, uint256 accruedInterest, uint256 interestIndex, uint256 lastInteraction) loan) view returns (uint256 cratio)',
  'function collateralRedeemed(bytes32 currency, uint256 amount) view returns (uint256 collateral)',
  'function deposit(address borrower, uint256 id, uint256 amount)',
  'function draw(uint256 id, uint256 amount)',
  'function getReward(bytes32 currency, address account)',
  'function interactionDelay() view returns (uint256)',
  'function isResolverCached() view returns (bool)',
  'function issueFeeRate() view returns (uint256)',
  'function liquidate(address borrower, uint256 id, uint256 amount)',
  'function liquidationAmount(tuple(uint256 id, address account, uint256 collateral, bytes32 currency, uint256 amount, bool short, uint256 accruedInterest, uint256 interestIndex, uint256 lastInteraction) loan) view returns (uint256 amount)',
  'function manager() view returns (address)',
  'function maxLoan(uint256 amount, bytes32 currency) view returns (uint256 max)',
  'function maxLoansPerAccount() view returns (uint256)',
  'function minCollateral() view returns (uint256)',
  'function minCratio() view returns (uint256)',
  'function nominateNewOwner(address _owner)',
  'function nominatedOwner() view returns (address)',
  'function open(uint256 collateral, uint256 amount, bytes32 currency)',
  'function owner() view returns (address)',
  'function rebuildCache()',
  'function repay(address borrower, uint256 id, uint256 amount)',
  'function resolver() view returns (address)',
  'function resolverAddressesRequired() view returns (bytes32[] addresses)',
  'function setCanOpenLoans(bool _canOpenLoans)',
  'function setInteractionDelay(uint256 _interactionDelay)',
  'function setIssueFeeRate(uint256 _issueFeeRate)',
  'function setManager(address _newManager)',
  'function setMinCratio(uint256 _minCratio)',
  'function shortingRewards(bytes32) view returns (address)',
  'function state() view returns (address)',
  'function synths(uint256) view returns (bytes32)',
  'function synthsByKey(bytes32) view returns (bytes32)',
  'function withdraw(uint256 id, uint256 amount)',
];
