// !!! DO NOT EDIT !!! Automatically generated file

export const name = 'PerpsV2MarketSettings';
export const address = '0x34ffA8af41B1B3077e7b40cC19B6906c3125Cd0c';
export const source = 'PerpsV2MarketSettings';
export const abi = [
  'constructor(address _owner, address _resolver)',
  'event CacheUpdated(bytes32 name, address destination)',
  'event KeeperLiquidationFeeUpdated(uint256 keeperFee)',
  'event LiquidationBufferRatioUpdated(uint256 bps)',
  'event LiquidationFeeRatioUpdated(uint256 bps)',
  'event MaxKeeperFeeUpdated(uint256 sUSD)',
  'event MinInitialMarginUpdated(uint256 minMargin)',
  'event MinKeeperFeeUpdated(uint256 sUSD)',
  'event OwnerChanged(address oldOwner, address newOwner)',
  'event OwnerNominated(address newOwner)',
  'event ParameterUpdated(bytes32 indexed marketKey, bytes32 indexed parameter, uint256 value)',
  'event ParameterUpdatedBytes32(bytes32 indexed marketKey, bytes32 indexed parameter, bytes32 value)',
  'function CONTRACT_NAME() view returns (bytes32)',
  'function acceptOwnership()',
  'function delayedOrderConfirmWindow(bytes32 _marketKey) view returns (uint256)',
  'function isResolverCached() view returns (bool)',
  'function keeperLiquidationFee() view returns (uint256)',
  'function liquidationBufferRatio(bytes32 _marketKey) view returns (uint256)',
  'function liquidationFeeRatio() view returns (uint256)',
  'function liquidationPremiumMultiplier(bytes32 _marketKey) view returns (uint256)',
  'function makerFee(bytes32 _marketKey) view returns (uint256)',
  'function makerFeeDelayedOrder(bytes32 _marketKey) view returns (uint256)',
  'function makerFeeOffchainDelayedOrder(bytes32 _marketKey) view returns (uint256)',
  'function maxDelayTimeDelta(bytes32 _marketKey) view returns (uint256)',
  'function maxFundingVelocity(bytes32 _marketKey) view returns (uint256)',
  'function maxKeeperFee() view returns (uint256)',
  'function maxLeverage(bytes32 _marketKey) view returns (uint256)',
  'function maxLiquidationDelta(bytes32 _marketKey) view returns (uint256)',
  'function maxMarketValue(bytes32 _marketKey) view returns (uint256)',
  'function maxPD(bytes32 _marketKey) view returns (uint256)',
  'function minDelayTimeDelta(bytes32 _marketKey) view returns (uint256)',
  'function minInitialMargin() view returns (uint256)',
  'function minKeeperFee() view returns (uint256)',
  'function nextPriceConfirmWindow(bytes32 _marketKey) view returns (uint256)',
  'function nominateNewOwner(address _owner)',
  'function nominatedOwner() view returns (address)',
  'function offchainDelayedOrderMaxAge(bytes32 _marketKey) view returns (uint256)',
  'function offchainDelayedOrderMinAge(bytes32 _marketKey) view returns (uint256)',
  'function offchainMarketKey(bytes32 _marketKey) view returns (bytes32)',
  'function offchainPriceDivergence(bytes32 _marketKey) view returns (uint256)',
  'function owner() view returns (address)',
  'function parameters(bytes32 _marketKey) view returns (tuple(uint256 takerFee, uint256 makerFee, uint256 takerFeeDelayedOrder, uint256 makerFeeDelayedOrder, uint256 takerFeeOffchainDelayedOrder, uint256 makerFeeOffchainDelayedOrder, uint256 maxLeverage, uint256 maxMarketValue, uint256 maxFundingVelocity, uint256 skewScale, uint256 nextPriceConfirmWindow, uint256 delayedOrderConfirmWindow, uint256 minDelayTimeDelta, uint256 maxDelayTimeDelta, uint256 offchainDelayedOrderMinAge, uint256 offchainDelayedOrderMaxAge, bytes32 offchainMarketKey, uint256 offchainPriceDivergence, uint256 liquidationPremiumMultiplier, uint256 liquidationBufferRatio, uint256 maxLiquidationDelta, uint256 maxPD))',
  'function rebuildCache()',
  'function resolver() view returns (address)',
  'function resolverAddressesRequired() view returns (bytes32[] addresses)',
  'function setDelayedOrderConfirmWindow(bytes32 _marketKey, uint256 _delayedOrderConfirmWindow)',
  'function setKeeperLiquidationFee(uint256 _keeperFee)',
  'function setLiquidationBufferRatio(bytes32 _marketKey, uint256 _ratio)',
  'function setLiquidationFeeRatio(uint256 _ratio)',
  'function setLiquidationPremiumMultiplier(bytes32 _marketKey, uint256 _liquidationPremiumMultiplier)',
  'function setMakerFee(bytes32 _marketKey, uint256 _makerFee)',
  'function setMakerFeeDelayedOrder(bytes32 _marketKey, uint256 _makerFeeDelayedOrder)',
  'function setMakerFeeOffchainDelayedOrder(bytes32 _marketKey, uint256 _makerFeeOffchainDelayedOrder)',
  'function setMaxDelayTimeDelta(bytes32 _marketKey, uint256 _maxDelayTimeDelta)',
  'function setMaxFundingVelocity(bytes32 _marketKey, uint256 _maxFundingVelocity)',
  'function setMaxKeeperFee(uint256 _sUSD)',
  'function setMaxLeverage(bytes32 _marketKey, uint256 _maxLeverage)',
  'function setMaxLiquidationDelta(bytes32 _marketKey, uint256 _maxLiquidationDelta)',
  'function setMaxMarketValue(bytes32 _marketKey, uint256 _maxMarketValue)',
  'function setMaxPD(bytes32 _marketKey, uint256 _maxPD)',
  'function setMinDelayTimeDelta(bytes32 _marketKey, uint256 _minDelayTimeDelta)',
  'function setMinInitialMargin(uint256 _minMargin)',
  'function setMinKeeperFee(uint256 _sUSD)',
  'function setNextPriceConfirmWindow(bytes32 _marketKey, uint256 _nextPriceConfirmWindow)',
  'function setOffchainDelayedOrderMaxAge(bytes32 _marketKey, uint256 _offchainDelayedOrderMaxAge)',
  'function setOffchainDelayedOrderMinAge(bytes32 _marketKey, uint256 _offchainDelayedOrderMinAge)',
  'function setOffchainMarketKey(bytes32 _marketKey, bytes32 _offchainMarketKey)',
  'function setOffchainPriceDivergence(bytes32 _marketKey, uint256 _offchainPriceDivergence)',
  'function setParameters(bytes32 _marketKey, tuple(uint256 takerFee, uint256 makerFee, uint256 takerFeeDelayedOrder, uint256 makerFeeDelayedOrder, uint256 takerFeeOffchainDelayedOrder, uint256 makerFeeOffchainDelayedOrder, uint256 maxLeverage, uint256 maxMarketValue, uint256 maxFundingVelocity, uint256 skewScale, uint256 nextPriceConfirmWindow, uint256 delayedOrderConfirmWindow, uint256 minDelayTimeDelta, uint256 maxDelayTimeDelta, uint256 offchainDelayedOrderMinAge, uint256 offchainDelayedOrderMaxAge, bytes32 offchainMarketKey, uint256 offchainPriceDivergence, uint256 liquidationPremiumMultiplier, uint256 liquidationBufferRatio, uint256 maxLiquidationDelta, uint256 maxPD) _parameters)',
  'function setSkewScale(bytes32 _marketKey, uint256 _skewScale)',
  'function setTakerFee(bytes32 _marketKey, uint256 _takerFee)',
  'function setTakerFeeDelayedOrder(bytes32 _marketKey, uint256 _takerFeeDelayedOrder)',
  'function setTakerFeeOffchainDelayedOrder(bytes32 _marketKey, uint256 _takerFeeOffchainDelayedOrder)',
  'function skewScale(bytes32 _marketKey) view returns (uint256)',
  'function takerFee(bytes32 _marketKey) view returns (uint256)',
  'function takerFeeDelayedOrder(bytes32 _marketKey) view returns (uint256)',
  'function takerFeeOffchainDelayedOrder(bytes32 _marketKey) view returns (uint256)',
];
