export const address = '0x94597307C9549c5BB03d1434dBb2301611ACaaB1';
export const abi = [
  'error InsufficientAccountCollateral(uint256 accountId, address collateralType, uint256 requestedAmount)',
  'error InvalidCollateralType(address collateralType)',
  'error InvalidParameters(string incorrectParameter, string help)',
  'error InvalidParameters(string incorrectParameter, string help)',
  'error MarketNotFound(uint256 marketId)',
  'error MaxDebtPerShareTooLow(uint256 marketId, int256 requestedMaxDebtPerShare, int256 maximumMaxDebtPerShare)',
  'error PermissionDenied(uint256 accountId, bytes32 permission, address target)',
  'error PoolAlreadyExists(uint256 poolId)',
  'error PoolNotFound(uint256 poolId)',
  'error Unauthorized(address addr)',
  'error ZeroAddress()',
  'event NominatedPoolOwner(uint256 indexed poolId, address indexed owner)',
  'event PoolConfigurationSet(uint256 indexed poolId, uint256[] indexed markets, uint256[] indexed weights, address executedBy)',
  'event PoolCreated(uint256 indexed poolId, address indexed owner)',
  'event PoolNameUpdated(uint256 indexed poolId, string indexed name, address indexed sender)',
  'event PoolNominationRenounced(uint256 indexed poolId, address indexed owner)',
  'event PoolNominationRevoked(uint256 indexed poolId, address indexed owner)',
  'event PoolOwnershipAccepted(uint256 indexed poolId, address indexed owner)',
  'event PoolOwnershipRenounced(uint256 indexed poolId, address indexed owner)',
  'function acceptPoolOwnership(uint256 poolId)',
  'function createPool(uint256 requestedPoolId, address owner)',
  'function getMinLiquidityRatio() view returns (uint256)',
  'function getNominatedPoolOwner(uint256 poolId) view returns (address)',
  'function getPoolConfiguration(uint256 poolId) view returns (uint256[], uint256[], int256[])',
  'function getPoolName(uint256 poolId) view returns (string poolName)',
  'function getPoolOwner(uint256 poolId) view returns (address)',
  'function nominatePoolOwner(address nominatedOwner, uint256 poolId)',
  'function renouncePoolNomination(uint256 poolId)',
  'function renouncePoolOwnership(uint256 poolId)',
  'function setMinLiquidityRatio(uint256 minLiquidityRatio)',
  'function setPoolConfiguration(uint256 poolId, uint256[] markets, uint256[] weights, int256[] maxDebtShareValues)',
  'function setPoolName(uint256 poolId, string name)',
];
