export const address = '0x670bff4C6CF9550a92A6847c9b77dA155F3dFeFc';
export const abi = [
  'error FailedTransfer(address from, address to, uint256 value)',
  'error InsufficientAccountCollateral(uint256 accountId, address collateralType, uint256 requestedAmount)',
  'error InvalidCollateral(address collateralType)',
  'error MismatchAssociatedSystemKind(bytes32 expected, bytes32 actual)',
  'error OutOfBounds()',
  'error PermissionDenied(uint256 accountId, bytes32 permission, address target)',
  'error PositionOutOfBounds()',
  'error Unauthorized(address addr)',
  'error ValueAlreadyInSet()',
  'event CollateralConfigured(address indexed collateralType, address indexed priceFeed, uint256 targetCollateralizationRatio, uint256 minimumCollateralizationRatio, uint256 liquidationReward, bool indexed enabled)',
  'event CollateralDeposited(uint256 indexed accountId, address indexed collateralType, uint256 amount, address indexed sender)',
  'event CollateralWithdrawn(uint256 indexed accountId, address indexed collateralType, uint256 amount, address indexed sender)',
  'function configureCollateral(address collateralType, address priceFeed, uint256 targetCRatio, uint256 minimumCRatio, uint256 liquidationReward, bool enabled)',
  'function depositCollateral(uint256 accountId, address collateralType, uint256 amount)',
  'function getAccountAvailableCollateral(uint256 accountId, address collateralType) view returns (uint256)',
  'function getAccountCollateral(uint256 accountId, address collateralType) view returns (uint256 totalStaked, uint256 totalAssigned)',
  'function getCollateralConfiguration(address collateralType) view returns (tuple(bool enabled, uint256 targetCRatio, uint256 minimumCRatio, uint256 liquidationReward, address priceFeed, address tokenAddress))',
  'function getCollateralConfigurations(bool hideDisabled) view returns (tuple(bool enabled, uint256 targetCRatio, uint256 minimumCRatio, uint256 liquidationReward, address priceFeed, address tokenAddress)[])',
  'function withdrawCollateral(uint256 accountId, address collateralType, uint256 amount)',
];
