export const address = '0xbcAe82DABb21E6211d952aFcc2742fd7F4737f88';
export const abi = [
  'error InsufficientAccountCollateral(uint256 accountId, address collateralType, uint256 requestedAmount)',
  'error InsufficientCollateralRatio(uint256 collateralValue, uint256 debt, uint256 ratio, uint256 minRatio)',
  'error InsufficientDebt(int256 currentDebt)',
  'error InvalidCollateral(address collateralType)',
  'error InvalidLeverage(uint256 leverage)',
  'error InvalidParameters(string incorrectParameter, string help)',
  'error InvalidParameters(string incorrectParameter, string help)',
  'error MarketNotFound(uint256 marketId)',
  'error MaxDebtPerShareTooLow(uint256 marketId, int256 requestedMaxDebtPerShare, int256 maximumMaxDebtPerShare)',
  'error MismatchAssociatedSystemKind(bytes32 expected, bytes32 actual)',
  'error PermissionDenied(uint256 accountId, bytes32 permission, address target)',
  'error PoolNotFound(uint256 poolId)',
  'event DelegationUpdated(uint256 indexed accountId, uint256 indexed poolId, address collateralType, uint256 amount, uint256 leverage, address indexed sender)',
  'event UsdBurned(uint256 indexed accountId, uint256 indexed poolId, address collateralType, uint256 amount, address indexed sender)',
  'event UsdMinted(uint256 indexed accountId, uint256 indexed poolId, address collateralType, uint256 amount, address indexed sender)',
  'function burnUsd(uint256 accountId, uint256 poolId, address collateralType, uint256 amount)',
  'function delegateCollateral(uint256 accountId, uint256 poolId, address collateralType, uint256 collateralAmount, uint256 leverage)',
  'function getPosition(uint256 accountId, uint256 poolId, address collateralType) returns (uint256 collateralAmount, uint256 collateralValue, int256 debt, uint256 collateralizationRatio)',
  'function getPositionCollateral(uint256 accountId, uint256 poolId, address collateralType) view returns (uint256 amount, uint256 value)',
  'function getPositionCollateralizationRatio(uint256 accountId, uint256 poolId, address collateralType) returns (uint256)',
  'function getPositionDebt(uint256 accountId, uint256 poolId, address collateralType) returns (int256)',
  'function getVaultCollateral(uint256 poolId, address collateralType) view returns (uint256 amount, uint256 value)',
  'function getVaultCollateralRatio(uint256 poolId, address collateralType) returns (uint256)',
  'function getVaultDebt(uint256 poolId, address collateralType) returns (int256)',
  'function mintUsd(uint256 accountId, uint256 poolId, address collateralType, uint256 amount)',
];
