export const address = '0xbA8403ea9784E756c9ee61DeA1143922dE958B77';
export const abi = [
  'error InvalidPermission()',
  'error MismatchAssociatedSystemKind(bytes32 expected, bytes32 actual)',
  'error OnlyAccountTokenProxy(address origin)',
  'error PermissionDenied(uint256 accountId, bytes32 permission, address target)',
  'error PermissionNotGranted(uint256 accountId, bytes32 permission, address target)',
  'error PositionOutOfBounds()',
  'error ValueAlreadyInSet()',
  'error ValueNotInSet()',
  'error ZeroAddress()',
  'event AccountCreated(address indexed sender, uint256 indexed accountId)',
  'event PermissionGranted(uint256 indexed accountId, bytes32 indexed permission, address indexed target, address sender)',
  'event PermissionRevoked(uint256 indexed accountId, bytes32 indexed permission, address indexed target, address sender)',
  'function createAccount(uint256 requestedAccountId)',
  'function getAccountOwner(uint256 accountId) view returns (address)',
  'function getAccountPermissions(uint256 accountId) view returns (tuple(address target, bytes32[] permissions)[] permissions)',
  'function getAccountTokenAddress() view returns (address)',
  'function grantPermission(uint256 accountId, bytes32 permission, address target)',
  'function hasPermission(uint256 accountId, bytes32 permission, address target) view returns (bool)',
  'function notifyAccountTransfer(address to, uint256 accountId)',
  'function renouncePermission(uint256 accountId, bytes32 permission)',
  'function revokePermission(uint256 accountId, bytes32 permission, address target)',
];
